# Generated by Django 3.1.6 on 2021-02-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.CharField(max_length=80),
        ),
    ]
