# Generated by Django 3.1.6 on 2021-02-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gameathlete',
            table='olympic_game_athlete',
        ),
    ]
