# Generated by Django 3.1.6 on 2021-02-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
