# Generated by Django 3.1.6 on 2021-02-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='athlete_id_ref',
            field=models.IntegerField(null=True),
        ),
    ]
