# Generated by Django 3.1.6 on 2021-02-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_auto_20210214_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(max_length=200),
        ),
    ]
