# Generated by Django 3.1.6 on 2021-02-11 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_auto_20210211_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
