# Generated by Django 3.1.6 on 2021-02-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_auto_20210210_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='medal',
            field=models.IntegerField(choices=[('NA', 'None'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')]),
        ),
    ]
