# Generated by Django 3.1.6 on 2021-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0002_auto_20210210_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='noc',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
