# Generated by Django 3.1.6 on 2021-02-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_athlete_athlete_id_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='athlete_id_ref',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
