# Generated by Django 3.1.6 on 2021-02-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_auto_20210210_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='medal',
            field=models.CharField(choices=[('NA', 'None'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=80),
        ),
    ]
