# Generated by Django 3.1.6 on 2021-02-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0003_auto_20210211_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='medal',
            field=models.CharField(choices=[('NA', 'None'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(max_length=200),
        ),
    ]
