# Generated by Django 3.1.6 on 2021-02-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_auto_20210211_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='name',
            field=models.CharField(max_length=199),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='city',
            field=models.CharField(max_length=203),
        ),
        migrations.AlterField(
            model_name='game',
            name='event',
            field=models.CharField(max_length=205),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=201),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.CharField(max_length=202),
        ),
        migrations.AlterField(
            model_name='game',
            name='sport',
            field=models.CharField(max_length=204),
        ),
    ]
