# Generated by Django 3.1.6 on 2021-02-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0004_auto_20210214_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='athlete_id_ref',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
