# Generated by Django 3.1.6 on 2021-02-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0005_auto_20210211_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='athlete_id_ref',
            field=models.IntegerField(null=True),
        ),
    ]
