# Generated by Django 3.1.6 on 2021-02-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympic', '0007_auto_20210212_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='medal',
            field=models.CharField(choices=[('None', 'None'), ('NA', 'None'), ('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=10, null=True),
        ),
    ]
